name: test kubectl

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: test alias
      run: make test-alias
    - name: ls
      run: make run-ls
